sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - make
script: make images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    make push
    make manifests
    fi
